version: '3.8'
services:
  db:
    # using this OOoooooold version of mysql because we can jsut connect with minimal code
    # Use a newer version for projectss!!! 
    image: mysql:5.7
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3306:3306
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted. A volume holds data locally.
      # This is persist your data when the conatiner is down
    env_file:
      - ./.env
    volumes:
      - data:/var/lib/mysql
  app:
    build: ./app
    env_file:
      - ./.env
    depends_on:
      - db
# Names our volume
volumes:
  data: 